---
# this is sorta hacky (and not idempotent) yumrepo module is released in Ansible v2.1

- name: install epel repository
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Add EPEL GPG key
  rpm_key:
    key: "{{ epel_gpg_url }}"
    state: present
